blueprints/methods_estudants.py
from flask import Blueprint, render_template, redirect, url_for, request
from helpers.database_handler import get_session_for_school, Matricula
from helpers.utils import check_token
from entry_data.entry_data import Register_Student

estudants_route = Blueprint('estudants', __name__)

@estudants_route.route('/<int:estudante_id>/update', methods=['GET', 'POST'])
def update_estudant(estudante_id):

    cookie_acess = request.cookies.get('acess_token')
    token_acess = check_token(cookie_acess)
    
    
    mapping_tokens = {
        'School Test': 'testschool'
    }
    
    session = get_session_for_school(mapping_tokens.get(token_acess.get('sub')))
    
    estudant = session.query(Matricula).filter_by(id=estudante_id).first()
    
    form = Register_Student(obj=estudant)
    
    
    if estudant:
        if request.method == 'POST':
            if form.validate_on_submit():
                estudant.aluno_name = form.aluno_name.data
                estudant.ano_letivo = form.ano_letivo.data
                estudant.status = form.status.data
                estudant.periodo_letivo = form.periodo_letivo.data
                estudant.modalidade = form.modalidade.data
                estudant.data_cancelamento = form.data_cancelamento.data
                estudant.notas_finais = form.notas_finais.data
                estudant.forma_pagamento = form.forma_pagamento.data
                estudant.observacoes = form.observacoes.data
                session.commit()
                return redirect(url_for('matriculas'))
            
    return render_template('create_matricula.html', form=form, estudant=estudant)

@estudants_route.route('/<int:estudante_id>/matrículas', methods=['GET', 'POST'])
def truncate(estudante_id):
    cookie_acess = request.cookies.get('acess_token')
    token_acess = check_token(cookie_acess)
    
    mapping_tokens = {
        'Colégio Dinâmico': 'colégiodinâmico',
        'School Test': 'testschool'
    }
    
    session = get_session_for_school(mapping_tokens.get(token_acess.get('sub')))
    
    estudant = session.query(Matricula).filter_by(id=estudante_id).first()
    print(estudant)
    
    if estudant:
        estudant.status = 'Trancada'
        session.commit()
        print(estudant.status)
        return redirect(url_for('matriculas'))
    
    
    return render_template('matriculas.html', estudante=estudant)
    

blueprints/render_routes.py
from flask import Blueprint, render_template

sidebar_route = Blueprint('sidebar', __name__)


@sidebar_route.route('/render-sidebar-html')
def render_sidebar():
    return render_template('sidebar.html')

templates/create_matricula.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Matrícula</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/criar-matricula.css') }}">
</head>
<body>
    
    <header class="__header">
        <h2 class="__header-title">{{'Criar Nova Matrícula' if not estudant else 'Editar Matrícula:'}} </h2>
        <button id="back-btn" onclick="window.history.back();">Voltar</button>
    </header>

    <main>
        <form method="POST" action="{{ url_for('add_matricula') if not estudant else url_for('estudants.update_estudant', estudante_id=estudant.id) }}" class="create-registration-form">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="aluno_name">Nome do Aluno:</label>
                {{ form.aluno_name(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="aluno_cpf">CPF do Aluno:</label>
                {{ form.cpf(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="ano_letivo">Ano Letivo:</label>
                {{ form.ano_letivo(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="status">Status:</label>
                {{ form.status(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="periodo_letivo">Período Letivo:</label>
                {{ form.periodo_letivo(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="modalidade">Modalidade:</label>
                {{ form.modalidade(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="data_cancelamento">Data de Cancelamento:</label>
                {{ form.data_cancelamento(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="notas_finais">Notas Finais:</label>
                {{ form.notas_finais(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="forma_pagamento">Forma de Pagamento:</label>
                {{ form.forma_pagamento(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="observacoes">Observações:</label>
                {{ form.observacoes(class="form-control") }}
            </div>
            <button type="submit" class="btn-submit"> {{'Criar Matrícula' if not estudant else 'Editar Matrícula'}} </button>
        </form>
    </main>
    <div c-container='{{url_for("sidebar.render_sidebar")}}'></div>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
    
</body>
</html>

templates/create_school.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Escolas - EduConnect</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/schools.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="error-message" class="hide">{{ error_message }}</div> <!-- Mensagem de erro -->
    <header class="__header">
        <h2 class="__header-title">Participe com a sua escola!</h2>
    </header>
    <hr class="line">
    <div c-container='{{url_for("sidebar.render_sidebar")}}'></div>
    <div class="container">
        <div class="header">
            <h1>Cadastro de Novas Escolas</h1>
        </div>
        <main class="main-content">
            <form class="school-form" action="schools" method="POST">
                {{ form.hidden_tag() }}
                <label for="school-name">Nome da Escola</label>
                {{ form.name(class="school-name", id="name", placeholder="Nome da Escola") }}
                
                <label for="school-address">CEP</label>
                {{ form.cep(class="school-adress", id="adress", placeholder="CEP. Ex: 00000000") }}
                
                <label for="school-phone">Telefone</label>
                {{ form.telephone(class="school-phone", id="phone", placeholder="Telefone de Contato. Ex: +55 (00) 0000-0000") }}
                
                <label for="school-email">E-mail</label>
                {{ form.email(class="school-email", id="email", placeholder="E-mail de contato") }}
                
                <button type="submit">Cadastrar</button>
            </form>
        </main>
    </div>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
    <script>
        window.onload = function () {
            error_message = document.querySelector('.error-message')
            if (error_message.textContent === 'None'){
                error_message.classList.add('hide')
            }
            else{
                error_message.classList.remove('hide')
                error_message.classList.add('show')
    
                setInterval(function(){
                    error_message.classList.remove('show')
                    error_message.classList.add('hide')
                }, 5000)
            }
            
        }
    </script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduConnect - Home</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    
    <header class="__header">
        <h2 class="__header-title">Quem somos?</h2>
    </header>
    <hr class="line">
    
    <div class="about">
        <div class="block-image">
            <img  src="{{ url_for('static', filename='images/educonnect.png') }}" alt="EduConnect Logo" class="logo">
        </div>
        <div class="block-about">
            <p class="about">
                EduConnect é a ponte que fortalece a comunicação entre estudantes, pais e escolas. Nossa plataforma oferece um serviço de excelência, garantindo uma conexão mais próxima e eficaz entre todos os envolvidos no processo educacional. Com o EduConnect, a vida escolar se torna mais acessível, engajadora e presente do que nunca!
            </p>
        </div>
    </div>
    <div c-container='{{url_for("sidebar.render_sidebar")}}'></div>

    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

templates/infos_alunos.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minha Matrícula</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/matriculas.css') }}">
</head>
<body>
    
    <header class="__header">
        <h2 class="__header-title">Sua Matrícula</h2>
    </header>

    <hr class="line">
    <div class="box-estudants">
        <div class="matricula-info">
            <span class="matricula-id">ID: {{ matricula.id }}</span>
            <span class="matricula-aluno">Nome: {{ matricula.aluno_name }}</span>
            <span class="matricula-cpf">CPF: {{ matricula.cpf }}</span>
            <span class="matricula-data">Data da Matrícula: {{ matricula.data_matricula }}</span>
            <span class="matricula-ano">Ano Letivo: {{ matricula.ano_letivo }}</span>
            <span class="matricula-status" id="{{ 'red' if matricula.status == 'Trancada' else '' }}">Status: {{ matricula.status }}</span>
            <span class="matricula-periodo">Período Letivo: {{ matricula.periodo_letivo }}</span>
            <span class="matricula-modalidade">Modalidade: {{ matricula.modalidade }}</span>
            <span class="matricula-cancelamento">Data de Cancelamento: {{ matricula.data_cancelamento }}</span>
            <p class="matricula-notas">{{ matricula.notas_finais | replace('\n', '<br>') | safe }}</p>
            <span class="matricula-pagamento">Forma de Pagamento: {{ matricula.forma_pagamento }}</span>
            <span class="matricula-observacao">Observações: {{ matricula.observacoes }}</span>
        </div>
    </div>

    <div c-container='{{url_for("sidebar.render_sidebar")}}'></div>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

templates/infos_createSchool.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduConnect - Página Inicial</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/infos_school.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <header class="__header">
        <h2 class="__header-title">Junte-se a nós!</h2>
    </header>
    <hr class="line">
    <div class="pre-container">
        <header class="pre-header">
            <h1>Bem-vindo ao EduConnect</h1>
            <p>Seu portal de conexão com escolas</p>
        </header>
        <main class="pre-main-content">
            <section class="info-section">
                <h2>Sobre o EduConnect</h2>
                <p>O EduConnect é um portal dedicado a facilitar a comunicação entre escolas e alunos, oferecendo uma plataforma intuitiva para gerenciar informações educacionais.</p>
            </section>
            <section class="cta-section">
                <h2>Cadastre uma nova escola</h2>
                <p>Quer adicionar uma nova escola ao nosso portal? Clique no botão abaixo para começar o processo de cadastro.</p>
                <a href="schools" class="cta-button">Cadastrar Escola</a>
            </section>
        </main>
    </div>
    <div c-container='{{url_for("sidebar.render_sidebar")}}'></div>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - EduConnect</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel="icon" href="{{url_for('static',  filename='images/educonnect.png')}}" type="image/x-icon">
</head>
<body>
    <div class="login-container">
        <div class="logo">
            <img src="{{ url_for('static', filename='images/educonnect.png') }}" alt="EduConnect Logo">
        </div>
        <h1>Bem-vindo novamente!</h1>
        <form action="login" method="POST">
            <div class="error-message" class="hide">{{ error_message }}</div>
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="dropdown">Selecione uma opção</label>
                {{ form.dropdown(class='form-control', id='dropdown') }}
            </div>
            <div class="form-group">
                <label for="cpf">CPF</label>
                {{ form.cpf(class='form-control', id='cpf', placeholder="Digite seu CPF") }}
            </div>
            <button type="submit">Entrar</button>
        </form>
    </div>
    
    <script>
        window.onload = function () {
            error_message = document.querySelector('.error-message')
            if (error_message.textContent === 'None'){
                error_message.classList.add('hide')
            }
            else{
                error_message.classList.remove('hide')
                error_message.classList.add('show')
    
                setInterval(function(){
                    error_message.classList.remove('show')
                    error_message.classList.add('hide')
                }, 5000)
            }
            
        }
    </script>
</body>
</html>

templates/matriculas.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/matriculas.css')}}">
</head>
<body>
    
    <header class="__header">
        <h2 class="__header-title">Suas Matrículas!</h2>
        <button id="new-registration-btn"><a href="add_matricula">Nova Matrícula</a></button>
    </header>

    <hr class="line">
    {% for m in matriculas %}
    <div class="box-estudants">
        <div class="matricula-info">
            <span class="matricula-id">ID: {{m.id}}</span>
            <span class="matricula-aluno">Nome: {{m.aluno_name}}</span>
            <span class="matricula-cpf">CPF: {{m.cpf}} </span>
            <span class="matricula-data">Data da Matrícula: {{m.data_matricula}}</span>
            <span class="matricula-ano">Ano Letivo: {{m.ano_letivo}}</span>
            <span class="matricula-status" id="{{'red' if m.status == 'Trancada' else ''}}">Status: {{m.status}}</span>
            <span class="matricula-periodo">Período Letivo: {{m.periodo_letivo}}</span>
            <span class="matricula-modalidade">Modalidade: {{m.modalidade}}</span>
            <span class="matricula-cancelamento">Data de Cancelamento: {{m.data_cancelamento}}</span>
            <p class="matricula-notas">{{ m.notas_finais | replace('\n', '<br>') | safe }}</p>
            <span class="matricula-pagamento">Forma de Pagamento: {{m.forma_pagamento}}</span>
            <span class="matricula-observacao">Observações: {{m.observacoes}}</span>
            <!-- Botões de ação -->
            <div class="matricula-actions">
                <button class="edit-btn"> <a href="{{url_for('estudants.update_estudant', estudante_id=m.id)}}">Editar Matrícula</a> </button>
                <button class="lock-btn"><a href="{{url_for('estudants.truncate', estudante_id=m.id)}}">Trancar Matrícula</a></button>
            </div>
        </div>
    </div>
    {% endfor %}

    <div c-container='{{url_for("sidebar.render_sidebar")}}'></div>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro - EduConnect</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <link rel="icon" href="{{url_for('static',  filename='images/educonnect.png')}}" type="image/x-icon">
</head>
<body>
    <div class="login-container">
        <div class="logo">
            <img src="{{ url_for('static', filename='images/educonnect.png') }}" alt="EduConnect Logo">
        </div>
        <h1>Bem-vindo ao EduConnect</h1>
        <form action="register" method="POST">
            {{ form.hidden_tag() }}
            <div class="error-message" class="hide">{{ error_message }}</div> <!-- Mensagem de erro -->
            <div class="form-group">
                <label for="username">Usuário</label>
                {{ form.name(class='form-control', id='username', placeholder="Digite seu nome") }}
            </div>
            <div class="form-group">
                <label for="password">Senha</label>
                {{ form.password(class="form-control", id="password", placeholder="Digite sua senha") }}
                <div id="password-requirements" class="requirements">
                </div>
            </div>

            <div class="form-group">
                <label for="repeat-password">Digite novamente a senha</label>
                {{ form.repeat_password(class="form-control", id="repeat-password", placeholder="Digite sua senha novamente") }}
            </div>

            <div class="form-group">
                <label for="email">E-mail</label>
                {{ form.email(class="form-control", id="email", placeholder="Digite seu email") }}
            </div>
            <button type="submit">Entrar</button>
        </form>
    </div>
    <script>
        window.onload = function () {
            error_message = document.querySelector('.error-message')
            if (error_message.textContent === 'None'){
                error_message.classList.add('hide')
            }
            else{
                error_message.classList.remove('hide')
                error_message.classList.add('show')
    
                setInterval(function(){
                    error_message.classList.remove('show')
                    error_message.classList.add('hide')
                }, 5000)
            }
            
        }
    </script>
</body>
</html>

templates/sidebar.html
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sidebar.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        
        .user-img {
            width: 50px;
            border-radius: 100%;
            border: 1px solid #eee;
        }
        
        
        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 250px;
            background-color: #22526d; /* Cor de fundo */
            padding: .4rem .8rem;
            transition: all 0.5s ease;
        }

        .sidebar .top .logo {
            display: flex;
            height: 50px;
            width: 100%;
            align-items: center;
            pointer-events: none;
        }

        .sidebar .top .logo i {
            min-width: 50px;
            text-align: center;
            height: 50px;
            border-radius: 12px;
            line-height: 50px;
        }

        .sidebar .top .logo .title-side {
            font-size: 25px;
        }

        .user {
            display: flex;
            align-items: center;
            margin: 1rem 0;
        }
        .user p {
            color: #fff;
            opacity: 1;
            margin-left: 1rem;
        }

        .bold {
            font-weight: 600;
        }

        .sidebar ul li {
            position: relative;
            list-style-type: none;
            height: 50px;
            width: 90%;
            margin: 0.8rem auto;
            line-height: 50px;
        }

        .sidebar ul li a {
            color: #fff;
            display: flex;
            align-items: center;
            text-decoration: none;
            border-radius: 0.8rem;
        }

        .sidebar ul li a:hover{
            background-color: #fff;
            color: #12171e;
        }

        .sidebar ul li a i {
            min-width: 50px;
            text-align: center;
            height: 50px;
            border-radius: 12px;
            line-height: 50px;
        }

        .sidebar ul li .tooltip {
            position: absolute;
            left: 125px;
            top: 50%;
            transform: translate(-50%, -50%);
            box-shadow: 0 0.5rem 0.8rem rgba(0, 0, 0, 0.2);
            border-radius: .6rem;
            padding: .4rem 1.2rem;
            line-height: 1.8rem;
            z-index: 20;
            opacity: 0;
        }

        .contact {
            display: flex;
            align-items: center;
            justify-content: center;
            margin-top: auto;
            font-size: 25px;
            color: #fff;
            opacity: 0.4;
            gap: 15;
        }

        a {
            color: inherit;
        }
    </style>
<body>
    <div class="sidebar">
        <div class="top">
            <div class="logo">
                <i class='bx bxs-graduation'></i>
                <span class="title-side"> EduConnect </span>
            </div>
            <div class="user">
                <img src="{{url_for('static', filename='images/educonnect.png')}}" alt="" class="user-img">
                <div>
                <p class="bold"></p>
                <p><b>Admin</b></p>
                </div>
            </div>
        </div>
            
        <ul class="list">
            <li>
                <a href="home">
                    <i class='bx bxs-dashboard' ></i>
                    Dashboard
                </a>
                <span class="tooltip">Dashboard</span>
            </li>
            <li>
                <a href="infos-school">
                    <i class='bx bxs-school'></i>
                    Junte-se
                </a>
                <span class="tooltip">Junte-se</span>
            </li>
            <li>
                <a href="info-aluno">
                    <i class='bx bxs-user-account'></i>
                    Seu perfil
                </a>
                <span class="tooltip">Seu perfil</span>
            </li>
            <li>
                <a href="matrículas">
                    <i class='bx bxs-user-check'></i>
                    Matrículas
                </a>
            </li>
            <li>
                <a href="logout">
                    <i class='bx bx-door-open' ></i>
                    Logout
                </a>
                <span class="tooltip">Logout</span>
            </li>
        </ul>
        <div class="contact">
           <a href="#">
            <i class='bx bxs-phone' ></i>
           </a>
           <a href="#">
            <i class='bx bxl-gmail' ></i>
           </a>
        </div>
    </div>
</body>
</html>